name: Cargo Build & Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install depdendencies.
        run: sudo apt-get install -y libfuse3-dev

      - name: Setup toolchain.
        run: |
          # Remove executables in order to have rustup manage the the tools.
          rm /home/runner/.cargo/bin/{rust-analyzer,rustfmt,cargo-fmt}
          # Bring up toolchain
          rustup update stable && rustup default stable

      - name: Build and test
        run: |
          cargo build --verbose
          cargo test --verbose
        env:
          RUSTFLAGS: "-D warnings"

      - name: Build and test release
        run: |
          cargo build --verbose --profile release
          cargo test --verbose --profile release
        env:
          RUSTFLAGS: "-D warnings"

      - name: Check docs
        run: cargo doc
        env:
          RUSTDOCFLAGS: "-D warnings"

      - name: Lint
        run: cargo clippy -- -D warnings
